// Generated by npm run tokens:generate from DESIGN.md. Do not edit.
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "!./src/components/ui/**"],
  theme: { extend: {
  "colors": {
    "background": "#090d12",
    "surface-950": "#020617",
    "surface-900": "#0f172a",
    "surface-panel": "#0f1720",
    "surface-panel-strong": "#050a10",
    "card": "#111923",
    "scrollbar-track": "#0d131a",
    "ink": "#f8f4ec",
    "ink-body": "#cbd5e1",
    "ink-muted": "#94a3b8",
    "primary": "#ff6238",
    "primary-hover": "#ff805e",
    "primary-focus": "#ff9b7e",
    "on-primary": "#020617",
    "success": "#34d399",
    "success-text": "#a7f3d0",
    "warning": "#fbbf24",
    "warning-text": "#fde68a",
    "danger": "#f43f5e",
    "danger-soft": "#fb7185",
    "danger-text": "#fecdd3",
    "danger-solid": "#e11d48",
    "on-danger": "#ffffff",
    "on-danger-soft": "#4c0519",
    "info": "#38bdf8",
    "info-text": "#bae6fd",
    "idle": "#64748b",
    "integration-services": "#60a5fa",
    "integration-services-text": "#bfdbfe",
    "integration-presentation": "#fdba74",
    "integration-presentation-text": "#fed7aa",
    "integration-lights": "#38bdf8",
    "integration-playback": "#e879f9",
    "integration-playback-text": "#f5d0fe",
    "advanced-services": "#84a4cc",
    "advanced-presentation": "#b4aaa4",
    "advanced-playback": "#ad96cc",
    "advanced-lights": "#78abcb",
    "edge-subtle": "#ffffff0f",
    "edge": "#ffffff1a",
    "edge-medium": "#ffffff2e",
    "live-go": "#34d399",
    "live-go-text": "#a7f3d0",
    "live-back": "#fdba74",
    "live-back-text": "#fed7aa",
    "live-reload": "#1d4ed8",
    "live-reload-text": "#bfdbfe",
    "live-stop": "#e11d48",
    "live-stop-text": "#fecdd3",
    "scrim": "#000000b3",
    "loader-track": "#07101f",
    "loader-outline": "#dbeafe",
    "loader-fill": "#38bdf8",
    "stage": {
      "700": "#223142",
      "800": "#17212c",
      "850": "#111923",
      "900": "#0d131a",
      "950": "#090d12"
    }
  },
  "fontFamily": {
    "type-brand": [
      "StagePilot Logo"
    ],
    "type-brand-hero": [
      "StagePilot Logo"
    ],
    "type-display-timer": [
      "ui-monospace"
    ],
    "type-song-title": [
      "Inter Variable"
    ],
    "type-text-strong": [
      "Inter Variable"
    ],
    "type-h1": [
      "Inter Variable"
    ],
    "type-h2": [
      "Inter Variable"
    ],
    "type-body-md": [
      "Inter Variable"
    ],
    "type-body-sm": [
      "Inter Variable"
    ],
    "type-label": [
      "Inter Variable"
    ],
    "type-kicker": [
      "Inter Variable"
    ],
    "type-badge": [
      "Inter Variable"
    ],
    "type-micro": [
      "Inter Variable"
    ]
  },
  "fontSize": {
    "type-brand": [
      "4.05rem",
      {
        "fontWeight": "400"
      }
    ],
    "type-brand-hero": [
      "11.25rem",
      {
        "fontWeight": "400"
      }
    ],
    "type-display-timer": [
      "5.4rem",
      {
        "letterSpacing": "-0.06em",
        "fontWeight": "300"
      }
    ],
    "type-song-title": [
      "3.65rem",
      {
        "letterSpacing": "-0.045em",
        "fontWeight": "900"
      }
    ],
    "type-text-strong": [
      "0.875rem",
      {
        "fontWeight": "700"
      }
    ],
    "type-h1": [
      "1.5rem",
      {
        "fontWeight": "700"
      }
    ],
    "type-h2": [
      "1.125rem",
      {
        "fontWeight": "700"
      }
    ],
    "type-body-md": [
      "0.875rem",
      {
        "fontWeight": "400"
      }
    ],
    "type-body-sm": [
      "0.75rem",
      {
        "fontWeight": "400"
      }
    ],
    "type-label": [
      "0.875rem",
      {
        "fontWeight": "600"
      }
    ],
    "type-kicker": [
      "0.6875rem",
      {
        "letterSpacing": "0.18em",
        "fontWeight": "800"
      }
    ],
    "type-badge": [
      "0.75rem",
      {
        "letterSpacing": "0.05em",
        "fontWeight": "700"
      }
    ],
    "type-micro": [
      "0.6875rem",
      {
        "letterSpacing": "0.05em",
        "fontWeight": "700"
      }
    ]
  },
  "borderRadius": {
    "ds-sm": "4px",
    "ds-md": "6px",
    "ds-lg": "8px",
    "ds-xl": "12px",
    "ds-2xl": "16px",
    "ds-full": "9999px",
    "ds-default": "8px"
  },
  "spacing": {
    "ds-xs": "4px",
    "ds-sm": "8px",
    "ds-md": "12px",
    "ds-lg": "16px",
    "ds-xl": "20px",
    "ds-2xl": "24px",
    "ds-touch-target": "44px",
    "ds-control": "36px"
  },
  "boxShadow": {
    "elevation-default": "inset 1px 1px 0 rgb(255 190 150 / 0.07), 2px 3px 6px rgb(33 15 13 / 0.35), 6px 10px 24px rgb(22 13 12 / 0.42), 12px 28px 64px rgb(22 13 12 / 0.45)",
    "elevation-overlay": "0 8px 24px rgb(22 13 12 / 0.45), 0 24px 80px rgb(22 13 12 / 0.60)",
    "elevation-level-1": "inset 1px 1px 0 rgb(255 190 150 / 0.07), 2px 3px 6px rgb(33 15 13 / 0.35), 6px 10px 24px rgb(22 13 12 / 0.42), 12px 28px 64px rgb(22 13 12 / 0.45)",
    "panel": "0 18px 50px rgba(0, 0, 0, 0.22)"
  }
} },
  // TODO Phase 3/surfaces: promote ds-default to DEFAULT after migrating bare rounded.
  // Dormant primitives/gallery are excluded until the surface migration.
  plugins: [function ({ addUtilities, addVariant }) {
    addUtilities({ ".text-shadow-label": { textShadow: "0 1px 2px rgb(10 10 12 / 0.55)" } });
    addVariant("coarse", "@media (pointer: coarse)");
    addVariant("can-hover", "@media (hover: hover) { &:hover }");
  }],
};
