import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { parse } from "yaml";
import process from "node:process";
import console from "node:console";

const frontend = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const design = resolve(frontend, "../DESIGN.md");
const source = readFileSync(design, "utf8");
const tokens = parse(source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)[1]);
// Use the installed, lockfile-pinned Google exporter; no network during regeneration.
const exported = JSON.parse(execFileSync(process.execPath, [
  resolve(frontend, "node_modules/@google/design.md/dist/index.js"),
  "export", "--format", "json-tailwind", design,
], { encoding: "utf8" })).theme.extend;
const colorName = (name) => name.replace(/^text(?=-|$)/, "ink")
  .replace(/^border(?=-|$)/, "edge").replace(/^panel(?=-|$)/, "surface-panel");
const prefixed = (values, prefix) => Object.fromEntries(
  Object.entries(values).map(([key, value]) => [`${prefix}${key}`, value]),
);
const extend = {
  ...exported,
  colors: Object.fromEntries(Object.entries(exported.colors).map(([k, v]) => [colorName(k), v])),
  // Never override stock rounded-*, spacing or font-brand in the plumbing phase.
  borderRadius: { ...prefixed(exported.borderRadius, "ds-"), "ds-default": tokens.rounded.lg },
  spacing: prefixed(exported.spacing, "ds-"),
  fontFamily: prefixed(Object.fromEntries(Object.entries(exported.fontFamily).map(
    ([k, v]) => [k, v.map((font) => font === "Inter" ? "Inter Variable" : font)],
  )), "type-"),
  fontSize: prefixed(exported.fontSize, "type-"),
  boxShadow: {
    "elevation-default": tokens.elevation.default,
    "elevation-overlay": tokens.elevation.overlay,
    "elevation-level-1": tokens["elevation-options"]["level-1"],
    // Compatibility only: migrate with surfaces, not plumbing.
    panel: "0 18px 50px rgba(0, 0, 0, 0.22)",
  },
};
extend.colors.stage = {
  950: tokens.colors.background,
  900: tokens.colors["scrollbar-track"],
  850: tokens.colors.card,
  // Unused compatibility shades have no design equivalents.
  800: "#17212c",
  700: "#223142",
};
const aliases = {
  bg: "var(--ds-background)",
  surface: "rgb(15 23 32 / 0.94)",
  "surface-strong": "rgb(5 10 16 / 0.9)",
  border: "rgb(255 255 255 / 0.09)",
  text: "var(--ds-ink)",
  "text-muted": "#9aa9bb",
  "text-quiet": "#718096",
  accent: "var(--ds-primary)",
  "accent-hover": "var(--ds-primary-hover)",
  "accent-subtle": "rgb(255 98 56 / 0.13)",
  focus: "var(--ds-primary-focus)",
  success: "#42dda4",
  warning: "#f6c453",
  danger: "var(--ds-danger-soft)",
  info: "#7dd3fc",
  "panel-shadow": "5px 6px 0 rgb(3 7 12 / 0.32), 0 18px 48px rgb(0 0 0 / 0.24)",
  "expressive-shadow": "var(--sp-panel-shadow)",
};
// Preserve exact authored alpha (the CLI rounds rgba colors to 8-digit hex).
const variables = Object.entries(tokens.colors).map(([k, v]) => `  --ds-${colorName(k)}: ${v};`);
for (const [k, v] of Object.entries(tokens.elevation)) variables.push(`  --ds-elevation-${k}: ${v};`);
variables.push(`  --ds-text-shadow-on-dark-text: ${tokens["text-shadow"]["on-dark-text"]};`);
for (const [k, v] of Object.entries(aliases)) {
  if (v.startsWith("var(")) variables.push(`  --sp-${k}: ${v};`);
  else {
    variables.push(`  --ds-compat-${k}: ${v};`);
    variables.push(`  --sp-${k}: var(--ds-compat-${k});`);
  }
}
const header = "// Generated by npm run tokens:generate from DESIGN.md. Do not edit.\n";
const config = `${header}/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],\n  theme: { extend: ${JSON.stringify(extend, null, 2)} },\n  // TODO Phase 3/surfaces: promote ds-default to DEFAULT after migrating bare rounded.\n  plugins: [function ({ addUtilities }) {\n    addUtilities({ ".text-shadow-label": { textShadow: ${JSON.stringify(tokens["text-shadow"]["on-dark-text"])} } });\n  }],\n};\n`;
const css = `/* Generated by npm run tokens:generate from DESIGN.md. Do not edit. */\n:root {\n${variables.join("\n")}\n}\n`;
let stale = false;
for (const [path, contents] of [["tailwind.config.js", config], ["src/design-tokens.css", css]]) {
  const target = resolve(frontend, path);
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== contents) { console.error(`Stale generated tokens: ${path}`); stale = true; }
  } else writeFileSync(target, contents);
}
if (stale) process.exitCode = 1;
else console.log(process.argv.includes("--check") ? "Design tokens are up to date." : "Design tokens generated.");
